module.exports = {
    filter: ".",
    indent: "    ",
    semverGroups: [],
    semverRange: "^",
    dependencyTyps: ["prod", "dev", "peer", "overrides", "resolutions", "pnpmOverrides"],
    sortAz: ["dependencies", "devDependencies", "peerDependencies"],
    sortFirst: [
        "name",
        "version",
        "publishConfig",
        "private",
        "keywords",
        "description",
        "author",
        "license",
        "repository",
        "homepage",
        "bugs",
        "scripts",
        "exports",
        "type",
        "main",
        "module",
        "types",
        "files",
        "dependencies",
        "devDependencies",
        "peerDependencies",
    ],
    source: [],
    versionGroups: [],
};
